apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::724772054315:role/eksctl-expense-1-nodegroup-expense-NodeInstanceRole-TcJdAQCEeGey
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - expense-trainee 
      userarn: arn:aws:iam::111122223333:user/suresh   
      username: suresh   
    - groups:
      - expense-admin
      userarn: arn:aws:iam::111122223333:user/ramesh  
      username: ramesh                 
kind: ConfigMap
metadata:
  creationTimestamp: "2025-11-25T05:13:39Z"
  name: aws-auth
  namespace: kube-system
  uid: 0496b759-e016-4e35-b6bb-216a31fe4a0e
